### ISSUE TITLE
Query inside folders recursively

### ISSUE THREAD

**Issue by ebezerra-it** [terence410/ts-google-drive#3]
Hi mate,
I need to search for files in a specific folder, also rescursively searching inside subfolders. I didnt find a way to do that in the current version. Am I right? I could create a brench with this feature and others if you want. Just let me know. Cheers.

**Comment by terence410** [comment]
let me take a look on the original library and get back to you.

**Comment by terence410** [comment]
https://stackoverflow.com/questions/46545336/search-files-recursively-using-google-drive-rest/46562607

it seems not possible to do recursive folder search in simple way
